export const CONTENT = {
  en: {
    nav: {
      logo: 'ScooPo',
      home: 'Home',
      about: 'About',
      services: 'Services',
      book: 'Book Now',
    },
    hero: {
      headline: 'We Scoop. We Remove. We Vacuum.',
      subhead: 'Melbourne’s only service that takes waste away AND vacuums.',
      cta: 'Book Your Clean',
    },
    features: {
      trash: { title: 'We Remove', desc: 'Complete pet waste removal from your property.' },
      vacuum: { title: 'We Vacuum', desc: 'Vacuuming scattered litter around the box.' },
      shield: { title: 'Hygienic', desc: 'Safe, sanitized, and pet-friendly process.' },
    },
    pricing: {
      essential: { name: 'Essential', price: '$25/Week', features: ['Cat Litter Removal', 'Litter Box Area Vacuum'] },
      care: { name: 'Premium', price: '$15/visit', features: ['Everything in Essential', 'Food & Water Refill'], popular: 'Most Popular' },
      ultimate: { name: 'Ultimate', price: '$20/visit', features: ['Everything in Premium', 'Food & Water Bowls Cleaning', 'Weekly Cat Litter Box Wash'] },
      btn: 'Choose Plan',
      frequency_label: 'Visits per week:',
      cats_label: 'Number of cats:',
      time_unit: 'Time',
      times_unit: 'Times',
      custom: '7+ (Custom Quote)',
      contact_btn: 'Contact for Quote',
    },
    footer: {
      contact: 'Serving Box Hill & Blackburn Area',
    },
    contact_form: {
      title: 'Have Questions?',
      subhead: 'Send us a message and we\'ll get back to you shortly.',
      name: 'Name',
      email: 'Email',
      message: 'Message',
      submit: 'Send Message',
      success: 'Message Sent!',
      loading: 'Sending...',
    },
    modal: {
      title: 'Book Service',
      name: 'Full Name',
      phone: 'Phone Number',
      email: 'Email Address',
      address: 'Property Address',
      plan: 'Select Plan',
      frequency: 'Frequency',
      cats: 'Number of Cats',
      submit: 'Confirm Booking',
      success: 'Booking Successful! We will contact you shortly.',
      error: 'Something went wrong. Please try again.',
      loading: 'Submitting...',
    }
  },
  cn: {
    nav: {
      logo: 'ScooPo',
      home: '首页',
      about: '关于我们',
      services: '服务详情',
      book: '立即预订',
    },
    hero: {
      headline: '清理、带走、吸尘',
      subhead: '墨尔本唯一一家提供清理带走并吸尘的服务。',
      cta: '预约清洁',
    },
    features: {
      trash: { title: '垃圾带走', desc: '从您的物业中彻底清除宠物垃圾。' },
      vacuum: { title: '吸尘服务', desc: '清理猫砂盆周围的散落猫砂。' },
      shield: { title: '卫生安全', desc: '安全、消毒，对宠物友好的流程。' },
    },
    pricing: {
      essential: { name: '基础版', price: '$25/周', features: ['猫砂清理', '猫砂盆区域吸尘'] },
      care: { name: '优享版', price: '$15/次', features: ['包含基础版所有服务', '添粮换水'], popular: '最受欢迎' },
      ultimate: { name: '尊享版', price: '$20/次', features: ['包含优享版所有服务', '饮食器具清洗', '每周清洗猫砂盆'] },
      btn: '选择方案',
      frequency_label: '每周服务次数：',
      cats_label: '猫咪数量：',
      time_unit: '次/周',
      times_unit: '次/周',
      custom: '7+ (定制方案)',
      contact_btn: '联系定制',
    },
    footer: {
      contact: '服务区域：Box Hill & Blackburn',
    },
    modal: {
      title: '预约服务',
      name: '姓名',
      phone: '电话',
      email: '电子邮箱',
      address: '地址',
      plan: '选择方案',
      frequency: '服务频率',
      cats: '猫咪数量',
      submit: '确认预约',
      success: '预约成功！我们将尽快联系您。',
      error: '出错了，请重试。',
      loading: '提交中...',
    },
    contact_form: {
      title: '有疑问吗？',
      subhead: '给我们留言，我们会尽快回复您。',
      name: '姓名',
      email: '电子邮箱',
      message: '留言内容',
      submit: '发送留言',
      success: '留言已发送！',
      loading: '发送中...',
    }
  }
};
